# Generated by Django 4.2.7 on 2023-11-23 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grade', '0003_remove_subject_student_id_subject_student'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Subject',
        ),
    ]
