# Generated by Django 4.2.7 on 2023-11-30 10:49

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grade', '0004_delete_subject'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='student_id',
        ),
        migrations.AddField(
            model_name='student',
            name='chinese_score',
            field=models.IntegerField(default=0, validators=[
                                      django.core.validators.MaxValueValidator(limit_value=100)]),
        ),
        migrations.AddField(
            model_name='student',
            name='english_score',
            field=models.IntegerField(default=0, validators=[
                                      django.core.validators.MaxValueValidator(limit_value=100)]),
        ),
        migrations.AddField(
            model_name='student',
            name='math_score',
            field=models.IntegerField(default=0, validators=[
                                      django.core.validators.MaxValueValidator(limit_value=100)]),
        ),
        migrations.AddField(
            model_name='student',
            name='physics_score',
            field=models.IntegerField(default=0, validators=[
                                      django.core.validators.MaxValueValidator(limit_value=100)]),
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('score', models.IntegerField(validators=[
                 django.core.validators.MaxValueValidator(limit_value=100)])),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                 related_name='subjects', to='grade.student')),
            ],
        ),
    ]
