# Generated by Django 4.2.7 on 2023-11-25 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grade', '0002_subject'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='student_id',
        ),
    ]
