# Generated by Django 4.2.7 on 2023-12-12 02:38

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('grade', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='student_id',
        ),
        migrations.AddField(
            model_name='student',
            name='chinese_score',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(limit_value=100)]),
        ),
        migrations.AddField(
            model_name='student',
            name='english_score',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(limit_value=100)]),
        ),
        migrations.AddField(
            model_name='student',
            name='math_score',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(limit_value=100)]),
        ),
        migrations.AddField(
            model_name='student',
            name='physics_score',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(limit_value=100)]),
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chinese_score', models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(limit_value=100)])),
                ('english_score', models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(limit_value=100)])),
                ('math_score', models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(limit_value=100)])),
                ('physics_score', models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(limit_value=100)])),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='course', to='grade.student')),
            ],
        ),
    ]
