# Generated by Django 4.2.7 on 2023-11-23 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grade', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('score', models.IntegerField()),
            ],
        ),
    ]
